spring:
  security:
    filter:
      order: -100
    jwt:
      key: ksafisoafjoasjfoasjs
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
#      password: 123456